#!/bin/zsh

# Function to find and activate venv
activate_venv() {
    local dir="$1"
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/venv" ]]; then
            source "$dir/venv/bin/activate" \
              && echo "Activated existing virtual environment." \
              || echo "Failed to activate virtual environment."
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

create_venv() {
    python3 -m venv venv/ &&
    source venv/bin/activate
}

# Find and activate venv if exists
if activate_venv "$(pwd)"; then
else
    echo "Virtual environment not found."
    if read -q "choice?Do you want to create a new one? [y/N]: "; then
        echo;
        create_venv &&
        echo "New virtual environment created and activated."
    else
        echo;
    fi
fi

