#!/bin/zsh

# Function to find and activate venv
activate_venv() {
    local dir="$1"
    while [[ "$dir" != "/" ]]; do
        if [[ -d "$dir/venv" ]]; then
            source "$dir/venv/bin/activate"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

# Find and activate venv if exists
if activate_venv "$(pwd)"; then
    echo "Activated existing virtual environment."
else
    echo "Virtual environment not found. Creating a new one..."
    python3 -m venv venv/
    source venv/bin/activate
    echo "New virtual environment created and activated."
fi

