#!/usr/bin/env zsh

set -euo pipefail
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"



cd ~/.config/
file=$(fzf --query ${1:-""})
exec "$EDITOR" "$file"
