#!/bin/bash

# check usage
if [[ $# -eq 0 ]]; then
    echo "usage: cenum [headers..] ENUM" >&2
    exit 1
fi

# generate temporary file
f=$(mktemp --suffix=.c)

# add headers
while [[ $# -gt 1 ]]; do
    echo '#include <'"$1"'>' >> "$f"
    shift
done

echo '#include <stdio.h>' >> $f
echo '#include <stdlib.h>' >> $f
echo '#include <string.h>' >> $f
echo '#include <signal.h>' >> $f
echo '#include <unistd.h>' >> $f
echo '#include <limits.h>' >> $f
echo '#include <float.h>' >> $f
echo '#include <sys/syscall.h>' >> $f
echo '#include <elf.h>' >> $f
echo 'int main() { printf("%1$d (0x%1$lx)\n", '"$1"'); }' >> "$f"

# compile and execute
gcc "$f" -o "$f.elf" && "$f.elf"

# remove temporary files
rm -f "$f" "$f.elf"
