#!/bin/bash

# Get the directory containing the current script
# and remove it from $PATH
dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
export PATH=$(echo $PATH | sed -e "s#:$dir##g" -e "s#$dir:##g" -e "s#$dir##g")

if [[ " $@ " =~ "-output-directory" ]]; then
    exec pdflatex "$@"
fi

tmpdir=$(mktemp -d)
trap "rm -rf $tmpdir" EXIT

pdflatex -output-directory "$tmpdir" "$@"
ret=$?

cp -rf "$tmpdir/"* .
exit $ret
