#!/usr/bin/env python3
"""
Process a pdf file for printing as a booklet.
"""
import os
import subprocess as sp
import shutil
import argparse
import tempfile
from pathlib import Path


STAPLE_TEX = r"""
\documentclass[a4paper,landscape]{article}
\usepackage{tikz}
\pagestyle{empty}

\begin{document}
\begin{tikzpicture}[remember picture,overlay]
  \draw[gray] (current page.north) ++ (0, -20mm) -- ++(0, -10.6mm);
  \draw[gray] (current page.south) ++ (0, 20mm) -- ++(0, 10.6mm);
\end{tikzpicture}
\end{document}
"""

def get_staple_pdf() -> Path:
    # Compile staple.pdf if necessary
    staple_tex_file = Path("staple.tex")
    staple_pdf_file = Path("/tmp/staple.pdf")

    if not staple_pdf_file.exists():
        with staple_tex_file.open('w') as tex_file:
            tex_file.write(STAPLE_TEX)
        print("-> compiling staple marks")
        try:
            sp.check_call(["pdflatex", "-halt-on-error", "-interaction=nonstopmode", staple_tex_file], stdin=sp.DEVNULL, stdout=sp.DEVNULL)
            sp.check_call(["pdflatex", "-halt-on-error", "-interaction=nonstopmode", staple_tex_file], stdin=sp.DEVNULL, stdout=sp.DEVNULL)
        except sp.CalledProcessError as e:
            print("Error compiling staple marks")
            print("----------------------------")
            with staple_tex_file.with_suffix(".log").open() as log_file:
                error = log_file.read()
                if "LaTeX Error: File `tikz.sty' not found." in error:
                    print("LaTeX Error: File `tikz.sty' not found.")
                    print()
                    print("For Debian/Ubuntu, install with\nsudo apt install texlive-pictures")

                print(log_file.read())
            raise e

        Path('staple.pdf').rename(staple_pdf_file)

    return staple_pdf_file


def main(input_file: Path, pages: str, margin: str, bound_box_vals: tuple[int, int, int, int]|None, bounding_box: str, no_bounding_box: str, output_file: Path|None, clip: bool, staple: bool) -> int|None:
    input_file = input_file.expanduser().resolve()

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir = Path(tmpdir)
        # Change to tmpdir
        os.chdir(tmpdir)

        xupped_file = tmpdir / f"{input_file.stem}_xup.pdf"
        stapled_file =tmpdir / f"{input_file.stem}_stapled.pdf"
        output_file = output_file or input_file.with_stem(f"{input_file.stem}_print")
        bb_args = ["-s"] + list(map(str, bound_box_vals)) if bound_box_vals else []

        pdflatex = shutil.which("pdflatex")
        pdfxup = shutil.which("pdfxup")
        pdftk = shutil.which("pdftk")
        
        missing_cmds = []
        missing_packages = []
        if not pdflatex:
            missing_cmds.append("pdflatex")
            missing_packages += ["texlive-latex-base", "texlive-pictures"]
        if not pdfxup:
            missing_cmds.append("pdfxup")
            missing_packages.append("texlive-extra-utils")
        if not pdftk and staple:
            missing_cmds.append("pdftk")
            missing_packages.append("pdftk")

        if missing_cmds:
            print("Missing commands: " + ", ".join(missing_cmds))
            print("For Ubuntu/Debian, install with:")
            print(f"sudo apt install {' '.join(missing_packages)}")
            return 1

        # Convert to booklet format
        pdfxup_args = ["bash", pdfxup,
                       "--booklet", "--paper", "a4", "-o", xupped_file,
                       *bb_args,
                       "-p", pages,
                       "-m", margin,
                       "-c" if clip else "-nc",
                       "--bb", bounding_box,
                       # "--nobb", no_bounding_box,
                       input_file]

        try:
            sp.check_call(pdfxup_args, stdin=sp.DEVNULL)

            if not staple:
                xupped_file.rename(output_file)
                return

            staple_pdf_file = get_staple_pdf()

            print("-> adding staple marks")
            assert pdftk is not None
            sp.check_call([pdftk, xupped_file, "stamp", staple_pdf_file, "output", stapled_file], stdin=sp.DEVNULL)
            sp.check_call([pdftk, f"A={stapled_file}", f"B={xupped_file}", "cat", "A1", "B2-end", "output", output_file], stdin=sp.DEVNULL)
        except sp.CalledProcessError as e:
            return e.returncode

def parse_bounding_box(s: str) -> tuple[int, int, int, int]:
    try:
        tup = tuple(map(int, s.split(",")))
    except ValueError:
        raise argparse.ArgumentTypeError(f"Invalid bounding box: {s} - expected 4 integers separated by commas")
    if len(tup) != 4:
        raise argparse.ArgumentTypeError(f"Invalid bounding box: {s} - expected 4 integers separated by commas")
    return tup

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input_file", type=Path, help="input PDF file")
    parser.add_argument("-bb", "--bounding-box", default="2-5", help="pages to use for computing bounding box")
    parser.add_argument("-nobb", "--no-bounding-box", default="", help="pages to omit when computing bounding box")
    parser.add_argument("-m", "--margin", default="3mm", help="margins")
    parser.add_argument("-p", "--pages", default="-", help="only include these pages")
    parser.add_argument("-o", "--output-file", type=Path, default=None, help="output file, default: <input_file>_print.pdf")
    parser.add_argument("-nc", "--no-clip", dest="clip", action="store_false", default=True, help="do not clip bounding box")
    parser.add_argument("-ns", "--no-staple", dest="staple", action="store_false", default=True, help="do not print staple marks on first page")

    # add mutually exclusive group --tosc and -s to specify bounding box
    bounding_box = parser.add_mutually_exclusive_group()
    bounding_box.add_argument("-s", dest="bounding_box_vals", type=parse_bounding_box, help="specify bounding box")
    bounding_box.add_argument("--tosc", dest="bounding_box_vals", action="store_const", const=(103, 103, 495, 740))

    args = parser.parse_args()

    ret = main(args.input_file, args.pages, args.margin, args.bounding_box_vals, args.bounding_box, args.no_bounding_box, args.output_file, args.clip, args.staple)
    raise SystemExit(ret)
