#!/bin/bash

set -euo pipefail

if test "$#" -eq 0; then
    echo "usage: $0 <dir> [rofi args]"
    exit 1
fi

cd "$1"
shift
find . -type f | grep '\.pdf$' | sort | sed 's#^\./##' | rofi -dmenu "$@" | xargs rifle
